# Generated by Django 4.0.4 on 2022-05-31 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encuestador',
            options={'verbose_name_plural': 'Encuestadores'},
        ),
    ]
